import {FluentPaletteColor} from './fluent-color';

export const fluentPaletteColorIntlFr = {
  "Red": 'Rouge',
  "Green": 'Vert',
  "DarkOrange": 'Orange foncé',
  "Yellow": 'Jaune',
  "Berry": 'baie',
  "LightGreen": 'vert clair',
  "Marigold": 'souci',
  "DarkRed": 'Rouge foncé',
  "Cranberry": 'canneberge',
  "Pumpkin": 'citrouille',
  "Peach": 'pêche',
  "Gold": 'Or',
  "Brass": 'laiton',
  "Brown": 'marron',
  "Forest": 'forêt',
  "Seafoam": 'écume de mer',
  "DarkGreen": 'vert foncé',
  "LightTeal": 'sarcelle clair',
  "Teal": 'sarcelle',
  "Steel": 'acier',
  "Blue": 'blue',
  "RoyalBlue": 'blue roi',
  "Cornflower": 'bleuet',
  "Navy": 'bleu marine',
  "Lavender": 'lavande',
  "Purple": 'violette',
  "Grape": 'raison',
  "Lilac": 'lilas',
  "Pink": 'rose',
  "Magenta": 'magenta',
  "Plum": 'Prune',
  "Beige": 'beige',
  "Mink": 'vison',
  "Platinum": 'platine',
  "Anchor": 'ancre'
,}
